import EvidenceLegend from '@/components/EvidenceLegend';

const principles = [
  ['AI agents are simulations, not humans.', 'Their behavior follows explicit model assumptions, not real cognition or real lived experience.'],
  ['Synthetic agent data is labelled.', 'Chennai population totals and city-service context are observed; individual agents and their behavioural variables are generated by the model.'],
  ['Uncertainty matters.', 'Seeds, parameters and model structure can change outcomes. Results should be compared across scenarios, not treated as certain predictions.'],
  ['Evidence boundaries matter.', 'Observed data, simulation results and model-inferred insights remain distinct throughout the product.'],
  ['Sensitive traits do not determine behaviour.', 'Population characteristics guide aggregate calibration, never fixed individual outcomes.'],
] as const;

const developers = ['Mahadevan Rajagopalan', 'Asvath M', 'Sanjit S', 'Krish Muralidharan', 'Sai retheka'];

export default function About() {
  return (
    <main className="page-shell">
      <div className="page-heading">
        <div>
          <div className="label">About PolicyForge</div>
          <h1>Decision support, not autonomous policymaking.</h1>
          <p>PolicyForge is a sandbox for exploring how a policy change might affect a Chennai-calibrated synthetic population. It does not decide policy or predict specific people.</p>
        </div>
      </div>
      <EvidenceLegend />
      <div className="stack">
        {principles.map(([title, body]) => (
          <section className="card p-7" key={title}>
            <h2 className="section-title ethics-title">{title}</h2>
            <p className="helper ethics-copy">{body}</p>
          </section>
        ))}
        <section className="card p-7 team-card">
          <div className="label">Project team</div>
          <h2 className="section-title ethics-title">Developed by</h2>
          <div className="team-list">{developers.map((developer) => <span key={developer}>{developer}</span>)}</div>
        </section>
      </div>
    </main>
  );
}
